version: '3.8'

name: lending-arbitrage
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "8001:3000" # Expose Grafana on port 8001
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090" # Expose Prometheus on port 9090
    volumes:
      - prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro # Add your Prometheus configuration file here
    networks:
      - monitoring

  valr-aave-arb:
    image: valr-aave-arb:latest
    container_name: valr-aave-arb
    restart: unless-stopped
    ports:
      - "3000:3000" # Expose the application on port 3000
    networks:
      - monitoring
    env_file: "docker-compose.env"

volumes:
  grafana:
    driver: local
  prometheus:
    driver: local

networks:
  monitoring:
    driver: bridge
