name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4.1.0
      with:
        node-version: 20.9.0
        cache-dependency-path: package-lock.json
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Compile project
      run: npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: typescript-build
        path: dist
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Download a dist artifact
      uses: actions/download-artifact@v4
      with:
        name: typescript-build
        path: dist
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: yashutanna/valr-aave-arbitrage:$(date +%s)
